repos:
  - repo: local
    hooks:
      - id: astyle
        name: astyle
        entry: astyle -Q -n
        args: ['--options=.astylerc']
        language: system
        types: [c]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-json
      - id: check-yaml
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
        exclude: ^(dist)
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: ['--fix=lf']
      - id: end-of-file-fixer
        exclude_types: [diff, image]
      - id: trailing-whitespace
        exclude_types: [diff, image]
      - id: forbid-submodules
